basePath: /
definitions:
  model.AddTaskRequest:
    properties:
      name:
        maxLength: 255
        type: string
    required:
    - name
    type: object
  model.AddTaskResponse:
    properties:
      id:
        type: integer
    type: object
  model.CreateListRequest:
    properties:
      name:
        maxLength: 255
        type: string
    required:
    - name
    type: object
  model.CreateListResponse:
    properties:
      id:
        type: integer
    type: object
  model.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  model.GetListByIDResponse:
    properties:
      list:
        $ref: '#/definitions/pkg_model.List'
    type: object
  model.HealthResponse:
    properties:
      status:
        type: string
    type: object
  pkg_model.List:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      tasks:
        items:
          $ref: '#/definitions/pkg_model.Task'
        type: array
    type: object
  pkg_model.Task:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    name: Misik Dmytro
    url: https://github.com/misikdmytro
  description: Task tracker service.
  title: Task Tracker API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: health check
      tags:
      - health
  /lists:
    put:
      consumes:
      - application/json
      description: create list
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateListRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.CreateListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: create list
      tags:
      - lists
  /lists/{id}:
    get:
      consumes:
      - application/json
      description: get list by id
      parameters:
      - description: list id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetListByIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: get list by id
      tags:
      - lists
  /lists/{id}/tasks:
    put:
      consumes:
      - application/json
      description: add task to list
      parameters:
      - description: list id
        in: path
        name: id
        required: true
        type: integer
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AddTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.AddTaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: add task to list
      tags:
      - lists
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: close task
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: close task
      tags:
      - lists
swagger: "2.0"
