name: Task Tracker CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
          - 1.19

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - run: go mod download
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: staticcheck ./...
      - run: go build ./cmd/app/main.go
      - run: docker compose build
      - run: docker compose up -d
      - run: go test -v ./test/...
      - run: docker compose down -v
        if: always()
